name: CI master push
run-name: ${{ github.actor }} pushed to master branch. 🚀 # optional
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get service name
        uses: actions/checkout@v3
        run: |
          echo "SERVICE=$(echo ${{ github.repository }} | cut -d '/' -f2)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Upload Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: immin5/${{ env.SERVICE }}:latest

      - name: Deploy
        run: |
          echo "Deploy"
