name: CI master push
run-name: ${{ github.actor }} pushed to master branch. 🚀 # optional
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'enter version(x.y.z)'
        required: true
        default: v1.0.0
  push:
    branches:
      - master

env:
  TAG: ${{ github.event.inputs.tag }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get service name
        run: |
          echo "SERVICE=$(echo ${{ github.repository }} | cut -d '/' -f2)" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Upload Docker Image Latest
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.SERVICE }}:latest

      - name: Upload Docker Image with Tag
        uses: docker/build-push-action@v2
        if: ${{ env.VERSION }}
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.SERVICE }}:${{ env.VERSION }}

      - name: Deploy
        run: |
          echo "Deploy"
          

  notification:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Slack
        if: always()
        uses: 8398a7/action-slack@v3.2.0
        with:
          status: ${{job.status}}
          fields: repo,message,commit,author,action,ref,workflow,job
          author_name: Github Action Slack