name: CI master push
run-name: ${{ github.actor }} pushed to master branch. 🚀 # optional
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get service name
        run: |
          echo "SERVICE=$(echo ${{ github.repository }} | cut -d '/' -f2)" >> $GITHUB_ENV

      - name: Upload Docker Image
        uses: docker/build-push-action@v1
        with:
          path: .
          repository: immin5/${{ env.SERVICE }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: latest

      - name: Deploy
        run: |
          echo "Deploy"
